name: Build Release ZIP

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build clean plugin ZIP
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          cd distributed-admin-theme
          zip -r ../distributed-admin-theme-${VERSION}.zip .

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: distributed-admin-theme-${{ github.ref_name }}.zip
          asset_path: distributed-admin-theme-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
